
import { ReactQueryProvider } from '@/components/ReactQueryProvier'
import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css'
import { Roboto } from 'next/font/google'
import Header from '@/components/Header'


const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ReactQueryProvider>
          <Header/>
        {children}
        </ReactQueryProvider>
        </body>
    </html>
  )
}
